openapi: 3.0.2
info:
  title: Users Service
  description: |-
    This is a simple App for demonstrating knowledge in API design skills
  contact:
    email: gino.luraschi@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
externalDocs:
  description: My github portfolio
  url: https://github.com/rlgino/
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: user
    description: Everything about your Users
paths:
  /user:
    post:
      tags:
        - user
      summary: Add a new user to the store
      description: Add a new user to the store
      operationId: addUser
      responses:
        '201':
          description: Successful operation
        default:
          description: The default operation result will be an error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      requestBody:
        description: Create a new user in the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'

  /user/{userID}:
    delete:
      tags:
        - user
      summary: Delete an user from storage
      description: Delete an user from storage, if the user not exists the endpoint will return 500
      operationId: deleteUser
      parameters:
        - name: userID
          in: path
          description: ID of user to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
        default:
          description: The default operation result will be an error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users:
    get:
      tags:
        - user
      summary: List stored users
      description: List the already stored users
      operationId: listUsers
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        default:
          description: The default operation result will be an error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'
    User:
      required:
        - id
        - name
        - password
      properties:
        id:
          type: string
          format: uuid
          example: 95854717-f395-455e-b610-95bd85d9adb1
        name:
          type: string
          example: test-user
        password:
          type: string
          example: mySecretPassword
      type: object
    Error:
      description: Represents error object
      type: object
      properties:
        message:
          type: string
          example: This is an clear error message
      required:
        - message
  requestBodies:
    User:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
      description: User object that needs to be added to the store