openapi: 3.0.2
info:
  title: Users Service
  description: |-
    This is a simple App for demostrating knowledge in API design skills
  contact:
    email: gino.luraschi@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
externalDocs:
  description: My github portfolio
  url: https://github.com/rlgino/
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: user
    description: Everything about your Users
paths:
  /user:
    post:
      tags:
        - user
      summary: Add a new user to the store
      description: Add a new user to the store
      operationId: addUser
      responses:
        '201':
          description: Successful operation
        default:
          description: ADJHKBKYUGFDSABHKGJYGHFSalJHGFBSDAUIL
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      requestBody:
        description: Create a new user in the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      required:
        - id
        - name
        - password
      properties:
        id:
          type: string
          example: doggie
        name:
          type: string
          example: doggie
        password:
          type: string
          example: mySecretPassword
      type: object
    Error:
      description: Represents error object
      type: object
      properties:
        message:
          type: string
      required:
        - message
  requestBodies:
    User:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
      description: User object that needs to be added to the store