version: "3"

services:
  backend-http:
    build: .
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - DATABASE_URL=${DATABASE_URL}
    # logging:
    #   driver: "loki"
    #   options:
    #     loki-url: http://localhost:3100/loki/api/v1/push

  backend-grpc:
    build:
      context: ./
      dockerfile: ./grpc.Dockerfile
    ports:
      - 3030:3030
    expose:
      - 3030
    environment:
      - DATABASE_URL=${DATABASE_URL}
    # logging:
    #   driver: "loki"
    #   options:
    #     loki-url: http://localhost:3100/loki/api/v1/push

  grafana:
    image: "grafana/grafana:8.4.2"
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning

  loki:
    image: "grafana/loki:2.4.2"
    ports:
      - "3100:3100"
