// Code generated by ogen, DO NOT EDIT.

package usersvcapi

import (
	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/validate"
)

func (s *User) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Status.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s UserStatus) Validate() error {
	switch s {
	case "ACTIVE":
		return nil
	case "INACTIVE":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
