// Code generated by ogen, DO NOT EDIT.

package usersvcapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddUser implements addUser operation.
//
// Add a new user to the store.
//
// POST /user
func (UnimplementedHandler) AddUser(ctx context.Context, req *User) error {
	return ht.ErrNotImplemented
}

// DeleteUser implements deleteUser operation.
//
// Delete an user from storage, if the user not exists the endpoint will return 500.
//
// DELETE /user/{userID}
func (UnimplementedHandler) DeleteUser(ctx context.Context, params DeleteUserParams) error {
	return ht.ErrNotImplemented
}

// FindUser implements findUser operation.
//
// Find a stored user.
//
// GET /user/{userID}
func (UnimplementedHandler) FindUser(ctx context.Context, params FindUserParams) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
